binary := `pwd` / ".." / "target" / "alpine-image-builder"
pwd    := `pwd`
target := "build"

default: build

[no-cd]
build:
    {{binary}} --config builder.toml --workdir "{{pwd}}" --output "{{target}}"

clean:
    rm -rf "{{target}}"
