binary := `pwd` / ".." / "target" / "alpine-image-builder"
pwd    := `pwd`
target := "build"
admin  := "doas"

default: build

[no-cd]
build:
    cd ../ && just
    {{binary}} --config builder.toml --workdir "{{pwd}}" --output "{{target}}"
    
deps:
    {{admin}} apk add alpine-sdk mtools dosfstools alpine-conf xorriso squashfs-tools grub grub-efi abuild abuild-rootbld mkinitfs-initramfs-cusp

clean:
    rm -rf "{{target}}"
