#!/bin/sh -e
BUILDDIR="$1"
PACKAGES="$HOME/.local/packages/"

errmsg() {
  echo
  echo "build failed:"
  echo $@
  echo
  exit 1
}

if [ -z "$BUILDDIR" ]; then
  errmsg "build dir required"
fi

BUILDDIR="$BUILDDIR/contents"
mkdir -p "$BUILDDIR"

_rsync() {
  if ! rsync -avc --delete-after --exclude="*/next*" "$PACKAGES" "$1"; then
    echo "failed to sync: $PACKAGES -> $1"
    exit 1
  fi
}

_rsync "cusp.ttypty.com:~/Hosted/"
_rsync "$BUILDDIR"

echo "-> Generating site content"
GENERATED="generated: $(date +%Y-%m-%dT%H:%M:%S)"
for DIR in $(find "$BUILDDIR" -type d); do
  DEST="$(echo "$DIR" | sed "s#$BUILDDIR##g")"
  {
  cat << EOF
<html>
<head><title>Index of $DEST</title></head>
<body bgcolor="white"><h1>Index of $DEST</h1><hr><pre>
EOF
  for FILE in "$DIR/"*; do
    BASE="$(basename "$FILE")"
    echo "$(stat -c '%y' "$FILE" | cut -d " " -f 1,2 | cut -d "." -f 1)&nbsp;<a href='$BASE'>$BASE</a>"

  done
  cat << EOF
</pre><hr>
<small>$GENERATED</small>
</body>
</html>
EOF
  } > "$DIR/index.html"
done

cp assets/* "$BUILDDIR"
