#!/bin/sh -e
BUILDDIR="$1"
CONF="$HOME/.abuild/abuild.conf"
if [ ! -e "$CONF" ]; then
  echo "no $CONF"
  exit 1
fi
source "$CONF"
PACKAGES="$REPOROOT/"

errmsg() {
  echo
  echo "build failed:"
  echo $@
  echo
  exit 1
}

if [ -z "$BUILDDIR" ]; then
  errmsg "build dir required"
fi

BUILDDIR="$BUILDDIR/contents"
mkdir -p "$BUILDDIR"
rsync -avc --delete-after --exclude="*/next*" "$PACKAGES" "$BUILDDIR"

DUPLICATES=$(
  {
    for FILE in $(find "$BUILDDIR" -type f -name "*.apk"); do
      DIR="$(dirname "$FILE")"
      NAME="$(basename "$FILE" | rev | cut -d "-" -f 3- | rev)"
      echo "$DIR/$NAME"
    done
  } | sort | uniq -d
)

if [ -n "$DUPLICATES" ]; then
  echo
  echo "duplicates detected:"
  echo "$DUPLICATES" | tr ' ' '\n' | sed 's/^/  - /g'
  errmsg "unable to post duplicate packages"
fi

echo "-> signing APKINDEX"
for DIR in $(find "$BUILDDIR" -type f -name "*.apk" -exec dirname {} \; | sort -u); do
  INDEX="$DIR/APKINDEX.tar.gz"
  rm "$INDEX"
  ARCH=$(basename "$DIR")
  (cd "$DIR" && apk index -d $(git describe 2>/dev/null) --rewrite-arch "$ARCH" --output APKINDEX.tar.gz *.apk)
  abuild-sign "$INDEX"
done

echo "-> Generating site content"
GENERATED="generated: $(date +%Y-%m-%dT%H:%M:%S)"
for DIR in $(find "$BUILDDIR" -type d); do
  DEST="$(echo "$DIR" | sed "s#$BUILDDIR##g")"
  {
  cat << EOF
<html>
<head><title>Index of $DEST</title></head>
<body bgcolor="white"><h1>Index of $DEST</h1><hr><pre>
EOF
  for FILE in "$DIR/"*; do
    BASE="$(basename "$FILE")"
    echo "$(stat -c '%y' "$FILE" | cut -d " " -f 1,2 | cut -d "." -f 1)&nbsp;<a href='$BASE'>$BASE</a>"

  done
  cat << EOF
</pre><hr>
<small>$GENERATED</small>
</body>
</html>
EOF
  } > "$DIR/index.html"
done

cp assets/* "$BUILDDIR"


ZIPTO="$PWD/$1/content.zip"
rm -f "$ZIPTO"
(cd "$BUILDDIR" && zip -r "$ZIPTO" .)
