#!/bin/sh -e
VIRTIO="Workspace Downloads Documents Active Env"

USER=""
while getopts "u:" opt ; do
  case $opt in
    u) USER="$OPTARG";;
    *)
      echo "unknown arg: $opt"
      ;;
  esac
done

if [ -z "$USER" ] || [ ! -d "/home/$USER" ]; then
  echo "no user given"
  exit 1
fi


for VIRT in $VIRTIO; do
  if grep "^$VIRT" -q /etc/fstab; then
    continue
  fi
  echo "$VIRT /home/$USER/$VIRT virtiofs    rw,nofail   0   0"
done

for LABEL in /dev/disk/by-label/is*; do
  BASE="$(basename "$LABEL")"
  PREFIX="LABEL=$BASE"
  if grep "^$PREFIX" -q /etc/fstab; then
    continue
  fi
  MOUNTPOINT=""
  FSTYPE="ext4"
  OPTIONS="defaults 0 0"
  case "$BASE" in
    "isswap")
      MOUNTPOINT=swap
      FSTYPE="swap"
      ;;
    "ishome")
      MOUNTPOINT="/home"
      ;;
    "isdata")
      MOUNTPOINT="/var"
      OPTIONS="defaults 1 2"
      ;;
    "isapkovl")
      MOUNTPOINT="/media/apkovl"
      OPTIONS="noauto,ro 0 0"
      ;;
  esac
  echo "$PREFIX $MOUNTPOINT $FSTYPE $OPTIONS"
done 
