#!/bin/sh -e
OVERLAY="/media/root-ro"
CONF=/etc/default/grub
if [ -d "$OVERLAY" ]; then
  echo "$OVERLAY already setup"
  exit 1 
fi

apk add apk-chroot

if grep "GRUB_CMDLINE_LINUX_DEFAULT" "$CONF" | grep -q "overlaytmpfs"; then
  echo "cmdline already set"
else
  echo "updating cmdline"
  sed -i "s/^GRUB_CMDLINE_LINUX_DEFAULT=\"/GRUB_CMDLINE_LINUX_DEFAULT=\"overlaytmpfs /g" "$CONF"
fi

grub-mkconfig -o /boot/grub/grub.cfg
