target := `pwd` / "build"
admin  := "doas"

default: build

[no-cd]
build:
    mkdir -p "{{target}}"
    ./make-image "{{target}}"
    ./disks "{{target}}"

deps:
    {{admin}} apk add alpine-sdk mtools dosfstools alpine-conf xorriso squashfs-tools grub grub-efi abuild abuild-rootbld

clean:
    rm -rf "{{target}}"
