#!/bin/sh -e
NAME="ttypty"
ARCH="aarch64"
TAG="3.20"
VERS="$TAG.3"
CUSP="https://dl-cdn.cusplinux.org/cusp/v$TAG"
ALPINE="https://dl-cdn.alpinelinux.org/alpine/v$TAG"
if [ -z "$1" ]; then
  echo "builddir required"
  exit 1
fi
BUILD="$1"
test -d "$BUILD"
WORKDIR="$(mktemp -d -t cusp-image.XXXXXX)"
trap 'rm -rf $WORKDIR' INT EXIT
CACHE="$BUILD/cache"
mkdir -p "$CACHE"

cp -r ../caports "$WORKDIR/"
SCRIPTS="$WORKDIR/caports/scripts"
PROFILE="mkimg.$NAME.sh"

{
  cat << EOF
profile_$NAME() {
  hostname="cusp.$NAME"
  modloop_sign=yes
  initfs_cmdline="modules=loop,squashfs,sd-mod,usb-storage quiet"
  initfs_features="ata base bootchart cdrom ext4 nvme squashfs usb virtio"
  grub_mod="all_video disk part_gpt part_msdos linux normal configfile search search_label efi_gop fat iso9660 cat echo ls test true help gzio"
  profile_abbrev="std"
  image_ext="iso"
  output_format="iso"
  title='$NAME'
  desc='$NAME personal spin iso'
  kernel_flavors='virt'
  profile_abbrev='$NAME'
  arch='$ARCH'
  kernel_addons=
EOF
  tr '\n' ' ' < "../caports/main/cusp-conf/world" | sed 's/^/  apks="/g;s/ $/"/g'
  echo
  echo "}"
} > "$SCRIPTS/$PROFILE"

(
  cd "$WORKDIR" && "caports/scripts/mkimage.sh" \
    --workdir "$CACHE" \
    --outdir "$BUILD" \
    --arch "$ARCH" \
    --profile "$NAME" \
    --tag "$VERS" \
    --hostkeys \
    --repository "$ALPINE/main" \
    --repository "$ALPINE/community" \
    --repository "$CUSP/main"
)
