#!/bin/sh -e
CONFIG="/etc/obu/env"
if [ ! -e "$CONFIG" ]; then
  echo "no $CONFIG found"
  exit 1
fi

for DIR in "$OVERLAY_MOUNT" "$OVERLAY_REDIRECT"; do
  if [ -d "$DIR" ]; then
    echo "unable to use: $DIR, already exists"
    exit 1
  fi
  mkdir -p "$DIR"
done

for MODULE in $OVERLAY_MODULES; do
  modprobe "$MODULE"
done

mount --bind / "$OVERLAY_REDIRECT"
mount "$OVERLAY_DEVICE" "$OVERLAY_MOUNT"


for DIR in $OVERLAY_DIRECTORIES; do
  OVERLAY="$OVERLAY_MOUNT/$DIR"
  UPPER="$OVERLAY/upperdir"
  WD="$OVERLAY/workdir"
  ROOTFS="$OVERLAY/rootfs"
  for SUB in "$UPPER" "$WD"; do
    if [ -d "$SUB" ]; then
      rm -rf "$SUB"
    fi
  done
  for SUB in "$UPPER" "$WD" "$ROOTFS"; do
    mkdir -p "$SUB"
  done
  mount -t overlay -o "lowerdir=$ROOTFS:$OVERLAY_MOUNT/$DIR,upperdir=$UPPER,workdir=$WD" "overlayfs-$DIR" "/$DIR"
done
